//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExternalWebhookReceiverAPI.Domain.Common.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class HotmartMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal HotmartMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ExternalWebhookReceiverAPI.Domain.Common.Resources.HotmartMessages", typeof(HotmartMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EXC0001 - Identifier não foi localizado na requisição..
        /// </summary>
        public static string EXC0001 {
            get {
                return ResourceManager.GetString("EXC0001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EXC0002 - Evento com Identifier {0} já existe para essa BusinessUnitId: {1}..
        /// </summary>
        public static string EXC0002 {
            get {
                return ResourceManager.GetString("EXC0002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EXC0003 - O campo {0} é obrigatório..
        /// </summary>
        public static string EXC0003 {
            get {
                return ResourceManager.GetString("EXC0003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EXC0004 - O campo {0} deve ser maior que zero..
        /// </summary>
        public static string EXC0004 {
            get {
                return ResourceManager.GetString("EXC0004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compra Aprovada.
        /// </summary>
        public static string HWB0001 {
            get {
                return ResourceManager.GetString("HWB0001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compra Cancelada.
        /// </summary>
        public static string HWB0002 {
            get {
                return ResourceManager.GetString("HWB0002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compra Completa.
        /// </summary>
        public static string HWB0003 {
            get {
                return ResourceManager.GetString("HWB0003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compra Boleto Registrado.
        /// </summary>
        public static string HWB0004 {
            get {
                return ResourceManager.GetString("HWB0004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compra Protestada.
        /// </summary>
        public static string HWB0005 {
            get {
                return ResourceManager.GetString("HWB0005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compra Reembolsada.
        /// </summary>
        public static string HWB0006 {
            get {
                return ResourceManager.GetString("HWB0006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compra Estornada.
        /// </summary>
        public static string HWB0007 {
            get {
                return ResourceManager.GetString("HWB0007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compra Expirada.
        /// </summary>
        public static string HWB0008 {
            get {
                return ResourceManager.GetString("HWB0008", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compra Adiada.
        /// </summary>
        public static string HWB0009 {
            get {
                return ResourceManager.GetString("HWB0009", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancelamento de Assinatura.
        /// </summary>
        public static string HWB0010 {
            get {
                return ResourceManager.GetString("HWB0010", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Troca de Plano.
        /// </summary>
        public static string HWB0011 {
            get {
                return ResourceManager.GetString("HWB0011", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abandono de Carrinho.
        /// </summary>
        public static string HWB0012 {
            get {
                return ResourceManager.GetString("HWB0012", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Troca do Dia de Cobrança de Assinatura.
        /// </summary>
        public static string HWB0013 {
            get {
                return ResourceManager.GetString("HWB0013", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Primeiro Acesso.
        /// </summary>
        public static string HWB0014 {
            get {
                return ResourceManager.GetString("HWB0014", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Módulo Completo.
        /// </summary>
        public static string HWB0015 {
            get {
                return ResourceManager.GetString("HWB0015", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Evento de {0} registrado com sucesso.
        /// </summary>
        public static string WebhookEventSuccess {
            get {
                return ResourceManager.GetString("WebhookEventSuccess", resourceCulture);
            }
        }
    }
}
