//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExternalWebhookReceiverAPI.Domain.Common.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class HotmartMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal HotmartMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ExternalWebhookReceiverAPI.Domain.Common.Resources.HotmartMessages", typeof(HotmartMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to Aprovada.
        /// </summary>
        public static string HWB0001
        {
            get
            {
                return ResourceManager.GetString("HWB0001", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to Cancelada.
        /// </summary>
        public static string HWB0002
        {
            get
            {
                return ResourceManager.GetString("HWB0002", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to Completa.
        /// </summary>
        public static string HWB0003
        {
            get
            {
                return ResourceManager.GetString("HWB0003", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to Boleto Registrado.
        /// </summary>
        public static string HWB0004
        {
            get
            {
                return ResourceManager.GetString("HWB0004", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to Protestado.
        /// </summary>
        public static string HWB0005
        {
            get
            {
                return ResourceManager.GetString("HWB0005", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to Reembolso.
        /// </summary>
        public static string HWB0006
        {
            get
            {
                return ResourceManager.GetString("HWB0006", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to Estornado.
        /// </summary>
        public static string HWB0007
        {
            get
            {
                return ResourceManager.GetString("HWB0007", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to Expirado.
        /// </summary>
        public static string HWB0008
        {
            get
            {
                return ResourceManager.GetString("HWB0008", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to Adiado.
        /// </summary>
        public static string HWB0009
        {
            get
            {
                return ResourceManager.GetString("HWB0009", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to Evento de compra {0} registrado com sucesso..
        /// </summary>
        public static string PurchaseEventSuccess
        {
            get
            {
                return ResourceManager.GetString("Evento de compra {0} registrado com sucesso.", resourceCulture);
            }
        }
    }
}
