name: Deploy ExternalWebhookReceiverAPI to Render

on:
  push:
    branches: [ "main" ]
    paths:
      - "ExternalWebhookReceiverAPI/**"
      - ".github/workflows/deploy-render.yml"
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout (with submodules)
        uses: actions/checkout@v4
        with:
          submodules: recursive

      # (Opcional) Validar build localmente
      - name: Docker build (optional smoke)
        run: |
          docker build \
            -f ExternalWebhookReceiverAPI/ExternalWebhookReceiverAPI.API/Dockerfile \
            -t external-webhook-receiver:ci \
            .

      - name: Prepare Render env payload
        id: envs
        run: |
          cat > env.json << 'JSON'
          {
            "envVars": [
              { "key": "ASPNETCORE_ENVIRONMENT", "value": "Production" },
              { "key": "ConnectionStrings__DefaultConnectionSqlServer", "value": "${{ secrets.SQLSERVER_CONNECTION }}" },
              { "key": "LoggingOptions__Url", "value": "${{ secrets.LOG_URL }}" }
            ]
          }
          JSON
          echo "payload=$(cat env.json)" >> $GITHUB_OUTPUT

      - name: Update Render env vars (overwrite)
        run: |
          curl -sS -X PUT "https://api.render.com/v1/services/${{ secrets.RENDER_SERVICE_ID }}/env-vars" \
            -H "Authorization: Bearer ${{ secrets.RENDER_API_KEY }}" \
            -H "Content-Type: application/json" \
            --data-binary @env.json
        # Atenção: este endpoint substitui TODAS as envs deste serviço (design da API do Render). :contentReference[oaicite:4]{index=4}

      - name: Trigger Render deploy (latest commit)
        run: |
          curl -sS -X POST "https://api.render.com/v1/services/${{ secrets.RENDER_SERVICE_ID }}/deploys" \
            -H "Authorization: Bearer ${{ secrets.RENDER_API_KEY }}" \
            -H "Content-Type: application/json" \
            -d '{"clearCache":"do_not_clear"}'
        # Endpoint oficial de trigger. :contentReference[oaicite:5]{index=5}