name: Keep Render Service Alive

on:
  schedule:
    # Executa a cada 5 minutos
    - cron: "*/5 * * * *"
  workflow_dispatch: # Permite rodar manualmente se quiser

jobs:
  keep-alive:
    runs-on: ubuntu-latest
    steps:
      - name: Pingar o endpoint /health
        run: |
          echo "Ping no Render para manter acordado..."
          curl -s -o /dev/null -w "%{http_code}" https://externalwebhookreceiverapi.onrender.com/health